"""Generate DOM-free ORTEP colors from the checked-in, case-sensitive source join.

No radii are imported. RGB decimals are rounded half-up to 8-bit channels.
Run from any directory; --check verifies the committed output without writing.
"""
import argparse
import csv
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'references' / 'ortep-colors'


def records(name):
    return [line.split() for line in (SOURCE / name).read_text(encoding='utf-8').splitlines()
            if line.strip() and not line.lstrip().startswith('#')]


def rgb(values):
    channels = [Decimal(value) for value in values]
    if len(channels) != 3 or any(not value.is_finite() or not 0 <= value <= 1 for value in channels):
        raise ValueError('Invalid source RGB')
    return '#' + ''.join(f'{int((value * 255).quantize(Decimal(1), rounding=ROUND_HALF_UP)):02x}' for value in channels)


def generate():
    colors = {}
    for name in ['rgbcols-base-1998.def', 'rgbcols-overrides.def']:
        for color, *values in records(name):
            colors[color] = rgb(values)  # Exact spelling: Lightblue does not replace LightBlue.
    atoms = records('atomcols.def')
    with (SOURCE / 'element-colors.csv').open(encoding='utf-8', newline='') as stream:
        rows = list(csv.DictReader(stream))
    if len(rows) != 108 or len(atoms) != 108 or len({row['symbol'] for row in rows}) != 108:
        raise ValueError('Expected all 108 unique original rows')
    entries = []
    for row, (symbol, color, *_radii) in zip(rows, atoms):
        if not re.fullmatch(r'[A-Z][a-z]?', symbol) or symbol == 'Db':
            raise ValueError('Unexpected source symbol')
        expected = colors[color]
        if (row['symbol'], row['color_name'], row['hex'].lower(), rgb([row[k] for k in ['r', 'g', 'b']])) != (symbol, color, expected, expected):
            raise ValueError(f'Source mismatch for {symbol}')
        entries.append(f"  {symbol}:'{expected}',")
    if colors['Pink'] != '#bc8f8f' or 'unknown = Pink' not in (SOURCE / 'atomcols.def').read_text(encoding='utf-8'):
        raise ValueError('Unknown-color declaration changed')
    return '\n'.join([
        '// Generated by scripts/generate-ortep-palette.py; do not choose replacement colors.',
        '// All 108 original ATOMCOLS.DEF rows joined to the case-sensitive RGB definitions',
        '// in references/ortep-colors (also independently tabulated in element-colors.csv).',
        '// RGB decimals use round(channel * 255); no radii are imported.',
        '// This reproduces the files, not a claim of verified ORTEP application behavior.',
        "export const ortepUnknownColor='#bc8f8f'; // Header declares unknown = Pink; base RGB dictionary.",
        'export const ortepPalette: Readonly<Record<string,string>>=Object.freeze({',
        *entries,
        '  // Modern Db aliases the legacy Ha row; Db is NOT a native source-table entry.',
        f"  Db:'{colors['Gray75']}'",
        '});',
        '',
    ])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'src' / 'ortep-palette.ts'
    text = generate()
    if args.check:
        if output.read_text(encoding='utf-8') != text:
            raise SystemExit('ORTEP palette differs; regenerate it')
        print('PASS ORTEP palette matches all original source rows')
    else:
        output.write_text(text, encoding='utf-8', newline='\n')
        print(output)
