// Experimental entry loader; build/ts is generated by npm run build.
// Avoid modifying the production package type or browser bundle entry points.
import {readFileSync} from 'node:fs';
import {resolve,dirname,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..','build','ts'),urls=new Map();
function moduleURL(file){
  file=resolve(root,file);if(!extname(file))file+='.js';if(urls.has(file))return urls.get(file);
  const source=readFileSync(file,'utf8').replace(/from\s+(['"])(\.\/[^'"]+)\1/g,(_,q,ref)=>`from ${q}${moduleURL(resolve(dirname(file),ref))}${q}`);
  const url='data:text/javascript;base64,'+Buffer.from(source).toString('base64');urls.set(file,url);return url;
}
export const load=(file)=>import(moduleURL(file));
